### ISSUE TITLE
Copy address to clipboard instead of bitcoin: uri scheme

### ISSUE THREAD

**Issue by cryptonaut420** [tokenly/swapbot#121]
Right now, the main vending/swap address that is displayed is just one of those <a href="bitcoin:
(address)" > URLs, however it doesnt make too much sense because you are essentially required to use a counterparty compatible wallet to receive and use your tokens anyways, and no counterparty wallet supports the bitcoin: URI scheme

What we need is just a little clipboard icon beside the address, which selects/highlights the address text when clicked, so that people can easily copy and paste it into their appropriate wallet. Currently it is kind of hard to highlight and copy the address at all actually

**Comment by AdamBLevine** [comment]
We already have this on step 3 and I'm not sure we want to make it easier (we might even want to remove it entirely from the front page) because we want people to use the interface for a variety of reasons

![image](https://cloud.githubusercontent.com/assets/6858319/8308745/5b89d1fa-197b-11e5-89f1-8004b14f5e54.png)

**Comment by deweller** [comment]
I replaced this with a semi-hidden copy-to-clipboard function.  We can ditch it later if we don't like it.
