### ISSUE TITLE
Need to prune bot events sent to the client

### ISSUE THREAD

**Issue by deweller** [tokenly/swapbot#126]
After a swapbot has been running for a while, many swaps can happen.

The client web page gets all of the data, including ALL past swap events for all swaps.  This is ok for a small number of swaps but will be unsustainable for larger swaps.

The server needs an option to send only the latest swap events for only the latest swaps when requested.

This problem is especially troublesome for swaps that error and retry multiple times.

**Comment by AdamBLevine** [comment]
I'd say limit to 10 + the ability to load more on a separate page? from that "Load More" button at the bottom

What number do you think is appropriate?  Or are you more talking about the admin backend that sees everything, because i'm seeing that right now on the LTBCOIN bot which I forgot to add a blacklisted address too and then funded with a million LTBc and it seems to still be sitting there not knowing what to do but caring.

**Comment by deweller** [comment]
I think 10 and the ability to load more on a separate page is a good plan.  And we can easily adjust this over time.

This issue is mostly about the server API delivering more data to the web page (or client) than it needs to.  In the case of failed swaps that keep retrying, this amount of data can be significant.  And it will grow over time for a swapbot that becomes popular.  We don't need, for example, to send data about a swap that happened 2 months ago.

**Comment by deweller** [comment]
Just another note, it looks like this is already causing issues in the admin application for swaps that had errors and many retries.

**Comment by deweller** [comment]
I loaded the extra swaps beyond 10 on the same page for now.  This was easier and felt appropriate for the first pass of functionality.

I think the separate page for a longer list of the swap history warrants some additional planning.  We will probably want a search and maybe some visual trends on that page.
