### ISSUE TITLE
Allow users to resume their place in Swapbot Popup

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#41]
In the full page version we had the ability for users to enter their bitcoin address and find their payment via that, in the popup version we do not have that ability.

On Step 2 it would be ideal let users put in their bitcoin address and the swapbot will either take them to the "this transaction is finished" page or put them back onto step 3 with the appropriate transaction selected.

Currently if you leave the popup there is no way to get it back on your transaction.

**Comment by deweller** [comment]
The working solution for this right now is to enter the amount you are trying to buy (rather than your source address).  You can see swaps in progress here (there may be multiple) and then click on the one you want to monitor.

Right now we are not planning have a filter by source address.  If think that is a necessity, please let Marcin and I know.

**Comment by AdamBLevine** [comment]
If it's easy to find your transaction and resume watching its progress by simply clicking on it, that solves the problem for my purposes.
