### ISSUE TITLE
Need the ability to charge fees to a platform address

### ISSUE THREAD

**Issue by deweller** [tokenly/swapbot#5]
We need to be able to assess fees on different bots based on the type of bot.  Some bots may be charged a 5% fee, while others take a 1% fee.

Should we take a fee of the incoming token?  Or the outgoing token?  Or both?

What if one of those tokens is not divisible?

**Comment by AdamBLevine** [comment]
I suggest we take a fee from the incoming token, the platform provides the service to the operator of the vending machine so it makes sense that they pay rather than it coming from the person buying from the vending machine.   The fee is a cost of doing business for you.

**Comment by AdamBLevine** [comment]
If the token is nondivisible, we'll either need to give people other options to pay the % with, I imagine this will be all the tokens we as Tokenly want to accept with discounts and premiums per normal.

Basically the swapbots logic would allocate some of the pay-token to the service based on valuations per transaction.   The advantage to the swapbot operator is they get 100% (no split) of what they receive for selling since it cannot be split and they'll have a lot of options of what to use to pay the fee.

**Comment by deweller** [comment]
Let's move this discussion to #10
