### ISSUE TITLE
Provide better reporting when out of BTC fuel

### ISSUE THREAD

**Issue by deweller** [tokenly/swapbot#7]
A counterparty send can fail if there is not enough BTC in the bot to power it.  When this happens, we need better reporting to notify the owner and/or user.

**Comment by AdamBLevine** [comment]
Two items
1 - Do we know exactly how much Bitcoin it takes per transaction?  If we do, we can show bot owners how many swaps worth of fuel are left rather than just an abstract number.  We can let them calculate how many transactions they want to charge it for, or just let them click a number and pop it to a payment page that says "Send x bitcoin to <address> to power the next <number of transactions> swaps.

2 - Are we able to use multisig outputs?  I know earlier in counterpartys life you could not use the multisig outputs you recieve as part of a counterparty transaction without doing a sort of manual recovery process.   Are we recovering this at all yet, and if not how difficult is it to fix the leak?

**Comment by deweller** [comment]
1) We do know how much BTC is required per transaction.  Note that this amount will change to be lower with the next counterparty release in 9.49.5 since multisig will no longer be necessary.

2) The leak still needs to be manually recovered.  Sends will use OP_RETURN in 9.49.5, so the leak will stop then.

**Comment by AdamBLevine** [comment]
Great, I wasn't aware of the upcoming change in 9.49.5
Are there any sacrifices anticipated from using the smaller op_return?

**Comment by deweller** [comment]
No.  The issue preventing it in the past was that some mining pools were not mining transactions with OP_RETURN.  But the number of pools still doing this appears to be insignificant now.

See https://github.com/CounterpartyXCP/counterpartyd/issues/690 for the discussion from the devs.

**Comment by deweller** [comment]
Completed by b3804a785ea2606958ae4c38aae2470eeb55bd55
